import type { Metadata } from "next";
import "./globals.css";

import { Gabarito, Josefin_Sans } from "next/font/google";
import { ThemeContextProvider } from "~/context";
import { Footer, Nav } from "~/components";

const fontHeading = Gabarito({
  variable: "--font-heading",
  subsets: ["latin"],
});

const fontBody = Josefin_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontHeading.variable} ${fontBody.variable}`}>
        <ThemeContextProvider>
          <Nav />
          <main>{children}</main>
          <Footer />
          <div className="gradient-container">
            <canvas className="gradient" id="gradient"></canvas>
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}

